#!/usr/bin/env bash
# Usage: ./mqtt-send -t "/t/o/p/i/c" -m "Message"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$DIR/../config/MQTT_CLI_CREDENTIALS"

/usr/bin/mosquitto_pub \
  -h mqtt.internal.0x08.in \
  -p 8883 \
  --cafile /etc/mosquitto/ca_certificates/ca.pem \
  -u $MQTT_CLI_USER \
  -P $MQTT_CLI_PASSWORD \
  $@
