#!/usr/bin/env bash
# Usage: ./mqtt-send -t "/t/o/p/i/c" -m "Message"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$DIR/../../../config/MQTT_CLI_CREDENTIALS"

/usr/bin/mosquitto_pub \
  -h 127.0.0.1 \
  -p 1883 \
  -u $MQTT_CLI_USER \
  -P $MQTT_CLI_PASSWORD \
  $@
