#!/usr/bin/env bash
DIR=`dirname $(realpath $0)`

# Open aquarium door (magnetic lock via intercom)
"$DIR/mqtt-send" -t 'modbus/endpointpp/set/aquarium_door_lock' -m '0'

# Power-up solenoid in red door lock mechanism for 1s
"$DIR/mqtt-send" -t 'modbus/endpointpp/set/red_door_lock' -m '1'
sleep 1
"$DIR/mqtt-send" -t 'modbus/endpointpp/set/red_door_lock' -m '0'

# KOZHANYE MESHKI need some time to move thru the doors
sleep 9

# Lock aquarium door
"$DIR/mqtt-send" -t 'modbus/endpointpp/set/aquarium_door_lock' -m '1'
